---
- hosts: mac  # Replace 'nodes' with the name of your target host or group
  tasks:
    - name: Get OS version on macOS
      shell: sw_vers
      register: os_version
      
    - name: Display OS version
      debug:
        var: os_version.stdout_lines
