- hosts: MAC
  tasks:
    - name: Stop Portainer
      become: yes
      become_user: "{{ ansible_user }}"
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
      command: "docker stop portainer"
