---
- hosts: MAC
  tasks:
    - name: Stop Minikube
      become: yes
      become_user: "{{ ansible_user }}"
      environment:
        DOCKER_EXECUTABLE: "/usr/local/bin/docker"
      command: "/usr/local/bin/minikube stop"
