---
- name: Stop All Docker Containers
  hosts: Mac
  tasks:
    - name: Get the ID of the Semaphore container
      shell: docker ps -q --filter "name=semaphore"
      register: semaphore_container_id
      ignore_errors: true

    - name: Stop all Docker containers except Semaphore
      shell: docker stop $(docker ps -q | grep -v "{{ semaphore_container_id.stdout }}")
      register: stopped_containers
      ignore_errors: true

    - name: Display the number of stopped containers
      shell: docker ps -a -f "status=exited" --format "{{.ID}}" | wc -l
      register: stopped_container_count
      ignore_errors: true

    - debug:
        msg: "Number of stopped containers: {{ stopped_container_count.stdout }}"
      when: stopped_container_count is succeeded
