---
- hosts: MAC
  tasks:
    - name: Stop EKS Cluster Nodes
      become: yes
      become_user: "{{ ansible_user }}"
      command: "/usr/local/bin/eksctl scale nodegroup --region eu-central-1 --name linux-nodes --nodes=0"
