---
- name: Stop EKS Cluster Nodes
  hosts: MAC
  gather_facts: false
  tasks:
    - name: Check if eksctl is installed
      command: "/opt/homebrew/bin/eksctl version"
      register: eksctl_installed
      ignore_errors: true
      changed_when: false

    - name: Update EKS Nodegroup Configuration
      command: >
        /opt/homebrew/bin/eksctl scale nodegroup --region eu-central-1 --name linux-nodes --nodes=0 --cluster eks-cluster
      register: scale_result
      changed_when: false

    - name: Check if nodegroup was scaled down successfully
      fail:
        msg: "Failed to scale down EKS cluster nodes"
      when: scale_result.rc != 0

  handlers:
    - name: Fail the playbook
      fail:
        msg: "Playbook failed. Check tasks for details."
      when: eksctl_installed.rc != 0 or scale_result.rc != 0
