---
- name: Stop All Docker Containers
  hosts: Mac
  tasks:
    - name: Get the ID of the Semaphore container
      shell: docker ps -q --filter "name=semaphore"
      register: semaphore_container_id
      ignore_errors: true

    - name: Stop all Docker containers except Semaphore
      shell: docker stop $(docker ps -q | grep -v "{{ semaphore_container_id.stdout }}")
      register: stopped_containers
      ignore_errors: true

    - name: Display the names of stopped containers
      shell: docker ps -a -f "status=exited" --format "{{.Names}}"
      register: stopped_container_names
      ignore_errors: true

    - debug:
        msg: "Stopped container names: {{ stopped_container_names.stdout_lines }}"
      when: stopped_container_names is succeeded
