- hosts: VM-1
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3  # Specify Python 3 interpreter if needed


