---
- hosts: VM-1  # Replace 'master' with the name of your target host or group
  tasks:
    - name: Get OS information
      shell: lsb_release -a
      register: os_info
      
    - name: Display OS information
      debug:
        var: os_info.stdout_lines
