- hosts: VM-1
  tasks:
    - name: Check if cluster-0 exists
      shell: "kind get clusters"
      register: clusters

    - name: Create kind-cluster-0
      become: yes
      become_user: "{{ ansible_ssh_user }}"
      environment:
        PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/bin"
      shell: |
        /usr/local/bin/kind create cluster --name cluster-0 --image kindest/node:v1.28.13
        sleep 30  # Wait for 30 seconds after the command runs
      when: "'cluster-0' not in clusters.stdout"

    - name: Update Helm repo
      shell: "helm repo update"
      args:
        chdir: "/home/dev/helm/repository"  # Adjust this if needed

    
